############################################################
# simulation command template
# - - ./simv
#   - -l
#   - sim.log
#   - -reportstats
############################################################
